config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path
    else
      render :new
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flats).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit this flat</h1>

<%= simple_form_for [@flat] do |f| %>
<%= f.input  :name %>
<%= f.input  :address %>
<%= f.input  :name %>
<%= f.input :description %>
<%= f.number_field :price_per_night %>
<%= f.number_field :number_of_guests %>
<%= f.submit "Edit flat", class: "btn" %>
<% end %>

app/views/flats/index.html.erb
<div class="to-flex">



<div class="header" style="text-shadow: 3px 1px #9b939378; margin-top: -100px; margin-bottom: 0px; "><h1 style="display: flex; font-size: 55px; font-family: 'Roboto', sans-serif; margin-left: 40px; margin-bottom: 0px;">All our flats</h1>
<span class="flat-count" style="display: flex; justify-content: end; text-shadow: 10px 10px 15px rgba(0,0,0,0.2);">Our (<%= @flats.count %>) flats</span>
</div>

<div class="all-cards">
  <% @flats.each do |flat| %>
    <div class="card-trip">
      <img src="https://picsum.photos/2000/3000?<%= rand(1..500) %>" />
      <div>
        <div class="card-trip-infos">
              <div class="card-container">
              <h2 class="card-h2"><%= link_to flat.name, flat_path(flat), class: "links", style: "text-shadow: 1px 1px #9b939378;" %></h2>
                <p><%= flat.address %></p>
                <p><%= flat.description %></p>
              </div>
            </div>
              <ul>
                <li class="card-trip-pricing">$<%= flat.price_per_night %></li>
                <li class="card-trip-pricing"><%= flat.number_of_guests %> 👤</li>
              </ul>
                <div class="footer">
              <%= link_to "More info", flat_path(flat), class: "links" %>
              <%= link_to "Edit", edit_flat_path(flat), class: "links" %>
              <%= link_to "Remove", flat_path(flat), method: :delete, data: {confirm: "You wanna delete your flat?"}, class: "links" %>
            </div>
          </div>
      </div>
  <% end %>
</div>



</div>

app/views/flats/show.html.erb
<h1>Show one flat</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-bar" style="position: sticky; top: 0px; padding-top: 2px; background-color: #d3d3d33d; backdrop-filter: blur(10px);">
      <div class="logo">
        <h2 style="border-bottom: 1px solid lightgray;
    padding-bottom: 17px; position: sticky; top: 0px; font-family: 'Roboto', sans-serif;"><%= link_to "AirBnB", flats_path, class: "links bold", style: " margin-left: 40px; text-shadow: 3px 1px #9b939378;" %></h2>
      </div>
    </div>



    <div class="container">
      <%= yield %>
    </div>


    <div class="footer-main">
    <div>
      <ul>
        <li class="footer-link"><a href="#">Mission</a></li>
        <li class="footer-link"><a href="#">Vision</a></li>
        <li class="footer-link"><a href="#">Contact Us</a></li>
        <li class="footer-link"><a href="#">Work With Us</a></li>
        <li class="footer-link"><a href="#">FAQ</a></li>
      </ul>
    </div>
    <%# <div>
        <ul>
          <li><a href="#"> <i class="fa fa-twitter-square" aria-hidden="true"></i> </a></li>
          <li><a href="#"> AAAAAAA </a></li>
          <li><a href="#"> WHY WONT YOU WORK </a></li>
        </ul>
    </div> %>
    </div>


  </body>



</html>